#!/bin/bash
echo "=== 检查服务状态 ==="
echo ""
echo "1. 证书文件:"
ls -lh /opt/xray-cluster/node/certs/ 2>/dev/null || echo "证书目录不存在"
echo ""
echo "2. Xray 容器状态:"
docker ps -a | grep xray-node-xray || echo "容器不存在"
echo ""
echo "3. Xray 日志 (最后20行):"
docker logs --tail 20 xray-node-xray 2>/dev/null || echo "无法获取日志"
echo ""
echo "4. 端口监听:"
netstat -tlnp 2>/dev/null | grep -E ':(80|443)' || ss -tlnp 2>/dev/null | grep -E ':(80|443)' || echo "无端口监听"
echo ""
echo "5. Xray 配置测试:"
docker exec xray-node-xray xray -test -config /etc/xray/config.json 2>&1 | head -10 || echo "无法测试配置"
